import type {
  ActivityItem,
  Deployment,
  Incident,
  MetricsSummary,
  Service,
  SystemSetting,
} from './types'

export const SERVICES: Service[] = [
  {
    id: 'svc-payments',
    name: 'payments-api',
    description: 'Card charges, refunds, and payout webhooks.',
    owner: 'Priya Nair',
    defaultBranch: 'main',
    branches: ['main', 'develop', 'release/2025-04'],
    status: 'healthy',
    version: '4.12.0',
    uptimePct30d: 99.98,
  },
  {
    id: 'svc-checkout',
    name: 'checkout-v2',
    description: 'Two-step checkout flow with wallet support.',
    owner: 'Amara Osei',
    defaultBranch: 'main',
    branches: ['main', 'main-next', 'feat/experiment-paypal-express-wallet-flow'],
    status: 'degraded',
    version: '3.9.4',
    uptimePct30d: 99.41,
  },
  {
    id: 'svc-search',
    name: 'search-index',
    description: 'Full-text and vector search over the catalog.',
    owner: 'Jones Lee',
    defaultBranch: 'main',
    branches: ['main', 'feat/hybrid-search'],
    status: 'healthy',
    version: '3.2.0',
    uptimePct30d: 99.95,
  },
  {
    id: 'svc-auth',
    name: 'auth-service',
    description: 'OIDC login, sessions, and API token exchange.',
    owner: 'Dana Kovac',
    defaultBranch: 'main',
    branches: ['main', 'release/2025-05'],
    status: 'healthy',
    version: '6.1.0',
    uptimePct30d: 99.99,
  },
  {
    id: 'svc-notifications',
    name: 'notification-pipeline',
    description: 'Fan-out email, push, and in-app notifications.',
    owner: 'Maria Lopez',
    defaultBranch: 'main',
    branches: ['main', 'fix/retry-storm'],
    status: 'degraded',
    version: '1.14.3',
    uptimePct30d: 99.12,
  },
  {
    id: 'svc-inventory',
    name: 'inventory-sync',
    description: 'Keeps stock levels consistent between warehouses.',
    owner: 'Maria Lopez',
    defaultBranch: 'main',
    branches: ['main', 'fix/consumer-retry'],
    status: 'down',
    version: '5.0.7',
    uptimePct30d: 97.84,
  },
  {
    id: 'svc-billing',
    name: 'billing-worker',
    description: 'Invoices, proration, and dunning retries.',
    owner: 'Priya Nair',
    defaultBranch: 'main',
    branches: ['main'],
    status: 'healthy',
    version: '2.2.9',
    uptimePct30d: 99.9,
  },
  {
    id: 'svc-media',
    name: 'media-cdn',
    description: 'Image optimization and global edge caching.',
    owner: 'Jones Lee',
    defaultBranch: 'main',
    branches: ['main', 'edge/upgrade'],
    status: 'healthy',
    version: '3.0.0-rc.2',
    uptimePct30d: 100,
  },
]

export const DEPLOYMENTS: Deployment[] = [
  {
    id: 'dep-4826',
    commit: 'a81f7c3',
    commitMessage: 'perf: batch webhook fan-out by tenant',
    serviceId: 'svc-payments',
    serviceName: 'payments-api',
    triggeredBy: 'Dana Kovac',
    trigger: 'push',
    environment: 'production',
    status: 'success',
    durationSec: 168,
    minutesAgo: 12,
  },
  {
    id: 'dep-4821',
    commit: '9f4d0b1',
    commitMessage: 'fix(billing): retry idempotency on 502s',
    serviceId: 'svc-payments',
    serviceName: 'payments-api',
    triggeredBy: 'Priya Nair',
    trigger: 'manual',
    environment: 'production',
    status: 'failed',
    durationSec: 214,
    minutesAgo: 47,
  },
  {
    id: 'dep-4819',
    commit: '7c2e9aa',
    commitMessage: 'feat: hybrid vector + BM25 scoring',
    serviceId: 'svc-search',
    serviceName: 'search-index',
    triggeredBy: 'Jones Lee',
    trigger: 'push',
    environment: 'production',
    status: 'success',
    durationSec: 201,
    minutesAgo: 185,
  },
  {
    id: 'dep-4818',
    commit: 'e3b8d10',
    commitMessage: 'chore: bump node to 22 in CI image',
    serviceId: 'svc-checkout',
    serviceName: 'checkout-v2',
    triggeredBy: 'Amara Osei',
    trigger: 'push',
    environment: 'staging',
    status: 'success',
    durationSec: 122,
    minutesAgo: 210,
  },
  {
    id: 'dep-4815',
    commit: 'c9a4f7e',
    commitMessage: 'fix: session refresh race on SSO tokens',
    serviceId: 'svc-auth',
    serviceName: 'auth-service',
    triggeredBy: 'Dana Kovac',
    trigger: 'schedule',
    environment: 'production',
    status: 'success',
    durationSec: 98,
    minutesAgo: 265,
  },
  {
    id: 'dep-4814',
    commit: 'b7e2a41',
    commitMessage: 'fix(consumer): exponential backoff on DLQ',
    serviceId: 'svc-inventory',
    serviceName: 'inventory-sync',
    triggeredBy: 'Maria Lopez',
    trigger: 'push',
    environment: 'preview',
    status: 'building',
    durationSec: 64,
    minutesAgo: 3,
  },
  {
    id: 'dep-4812',
    commit: 'f1d8c39',
    commitMessage: 'chore: rotate edge TLS certs',
    serviceId: 'svc-media',
    serviceName: 'media-cdn',
    triggeredBy: 'Jones Lee',
    trigger: 'schedule',
    environment: 'production',
    status: 'success',
    durationSec: 57,
    minutesAgo: 320,
  },
  {
    id: 'dep-4811',
    commit: '6a5b9d2',
    commitMessage: 'feat(proration): mid-cycle plan upgrades',
    serviceId: 'svc-billing',
    serviceName: 'billing-worker',
    triggeredBy: 'Priya Nair',
    trigger: 'manual',
    environment: 'staging',
    status: 'success',
    durationSec: 143,
    minutesAgo: 360,
  },
  {
    id: 'dep-4809',
    commit: 'd4c7e18',
    commitMessage: 'feat(payments): add PayPal express checkout',
    serviceId: 'svc-checkout',
    serviceName: 'checkout-v2',
    triggeredBy: 'Amara Osei',
    trigger: 'push',
    environment: 'production',
    status: 'failed',
    durationSec: 188,
    minutesAgo: 420,
  },
  {
    id: 'dep-4807',
    commit: '3e2f9b6',
    commitMessage: 'fix: suppress duplicate in-app banners',
    serviceId: 'svc-notifications',
    serviceName: 'notification-pipeline',
    triggeredBy: 'Maria Lopez',
    trigger: 'push',
    environment: 'staging',
    status: 'success',
    durationSec: 117,
    minutesAgo: 500,
  },
  {
    id: 'dep-4804',
    commit: '8b6a2c4',
    commitMessage: 'test: cover refund partial-capture paths',
    serviceId: 'svc-payments',
    serviceName: 'payments-api',
    triggeredBy: 'Dana Kovac',
    trigger: 'push',
    environment: 'staging',
    status: 'success',
    durationSec: 135,
    minutesAgo: 580,
  },
  {
    id: 'dep-4803',
    commit: '5d1e3a7',
    commitMessage: 'feat: reindex product taxonomy v8',
    serviceId: 'svc-search',
    serviceName: 'search-index',
    triggeredBy: 'Jones Lee',
    trigger: 'schedule',
    environment: 'production',
    status: 'building',
    durationSec: 38,
    minutesAgo: 1,
  },
  {
    id: 'dep-4801',
    commit: '2c8b4f9',
    commitMessage: 'chore: tighten token TTL to 15m',
    serviceId: 'svc-auth',
    serviceName: 'auth-service',
    triggeredBy: 'Dana Kovac',
    trigger: 'push',
    environment: 'preview',
    status: 'success',
    durationSec: 89,
    minutesAgo: 660,
  },
  {
    id: 'dep-4798',
    commit: 'b9d3e71',
    commitMessage: 'fix: dedupe warehouse heartbeats',
    serviceId: 'svc-inventory',
    serviceName: 'inventory-sync',
    triggeredBy: 'Priya Nair',
    trigger: 'manual',
    environment: 'production',
    status: 'success',
    durationSec: 176,
    minutesAgo: 740,
  },
  {
    id: 'dep-4796',
    commit: '4f7c1b8',
    commitMessage: 'chore: tune cache TTL for video thumbs',
    serviceId: 'svc-media',
    serviceName: 'media-cdn',
    triggeredBy: 'Jones Lee',
    trigger: 'push',
    environment: 'staging',
    status: 'success',
    durationSec: 104,
    minutesAgo: 820,
  },
]

export const ACTIVITY: ActivityItem[] = [
  {
    id: 'act-264',
    kind: 'deploy',
    title: 'payments-api @a81f7c3 promoted to production',
    user: 'Dana Kovac',
    minutesAgo: 12,
    tone: 'success',
  },
  {
    id: 'act-263',
    kind: 'deploy',
    title: 'payments-api build #4821 failed in CI (billing.spec.ts)',
    user: 'Priya Nair',
    minutesAgo: 47,
    tone: 'danger',
  },
  {
    id: 'act-262',
    kind: 'incident',
    title: 'SEV2 acknowledged — inventory-sync event backlog',
    user: 'Maria Lopez',
    minutesAgo: 80,
    tone: 'warning',
  },
  {
    id: 'act-261',
    kind: 'deploy',
    title: 'search-index v3.2.0 rolled out to production',
    user: 'Jones Lee',
    minutesAgo: 185,
    tone: 'success',
  },
  {
    id: 'act-260',
    kind: 'rollback',
    title: 'checkout-v2 rolled back to v3.9.2 after error spike',
    user: 'Amara Osei',
    minutesAgo: 255,
    tone: 'warning',
  },
  {
    id: 'act-259',
    kind: 'incident',
    title: 'SEV3 closed — notification-pipeline retry storm',
    user: 'Maria Lopez',
    minutesAgo: 330,
    tone: 'neutral',
  },
  {
    id: 'act-258',
    kind: 'config',
    title: 'Feature flag “fast-cart” enabled for 20% of traffic',
    user: 'Jones Lee',
    minutesAgo: 430,
    tone: 'neutral',
  },
  {
    id: 'act-257',
    kind: 'deploy',
    title: 'auth-service v6.1.0 deployed to staging',
    user: 'Dana Kovac',
    minutesAgo: 545,
    tone: 'success',
  },
]

export const INCIDENTS: Incident[] = [
  {
    id: 'inc-1042',
    code: 'INC-1042',
    title: 'inventory-sync event backlog exceeding 5 minutes',
    severity: 'SEV2',
    status: 'investigating',
    openedBy: 'Maria Lopez',
    minutesAgo: 80,
  },
  {
    id: 'inc-1041',
    code: 'INC-1041',
    title: 'checkout-v2 error spike after v3.9.4 rollout',
    severity: 'SEV3',
    status: 'resolved',
    openedBy: 'Amara Osei',
    minutesAgo: 260,
  },
  {
    id: 'inc-1040',
    code: 'INC-1040',
    title: 'Payment webhook retries saturating the queue',
    severity: 'SEV2',
    status: 'resolved',
    openedBy: 'Priya Nair',
    minutesAgo: 335,
  },
  {
    id: 'inc-1039',
    code: 'INC-1039',
    title: 'CDN cache purge latency above SLA in EU-West',
    severity: 'SEV3',
    status: 'resolved',
    openedBy: 'Jones Lee',
    minutesAgo: 1460,
  },
]

export const SYSTEM_SETTINGS: SystemSetting[] = [
  {
    id: 'set-approval',
    label: 'Production deploy approvals',
    description: 'Require a second approver for every production release.',
    enabled: true,
  },
  {
    id: 'set-rollback',
    label: 'Auto-rollback on error spikes',
    description: 'Revert automatically when error rates exceed 2% for 10 minutes.',
    enabled: true,
  },
  {
    id: 'set-digest',
    label: 'Weekly metrics digest',
    description: 'Email a summary of team reliability on Monday mornings.',
    enabled: false,
  },
  {
    id: 'set-paging',
    label: 'Incident paging',
    description: 'Page the on-call engineer for unresolved SEV2+ incidents.',
    enabled: true,
  },
  {
    id: 'set-preview',
    label: 'Preview environment expiry',
    description: 'Tear down preview environments after 72 hours of inactivity.',
    enabled: true,
  },
  {
    id: 'set-status',
    label: 'Public status page',
    description: 'Publish uptime and incident history to status.pulsometrics.app.',
    enabled: false,
  },
]

export const METRICS_BY_TEAM: Record<string, MetricsSummary> = {
  core: {
    updatedAt: Date.now() / 1000,
    cards: [
      {
        id: 'successRate',
        label: 'Deploy success rate',
        value: '99.2%',
        rawValue: 99.2,
        changePct: -0.4,
        positive: false,
        hint: '30-day rolling window',
        samples: [98, 99, 98, 99, 100, 99, 97, 98, 100, 99, 96, 98, 100, 99, 97, 98, 100, 99, 98, 100, 97, 99, 100, 98, 99, 97, 98, 100, 98, 99],
      },
      {
        id: 'activeServices',
        label: 'Active services',
        value: '12',
        rawValue: 12,
        changePct: 8.3,
        positive: true,
        hint: '+1 this month',
        samples: [10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
      },
      {
        id: 'errorBudget',
        label: 'Error budget left',
        value: '76.4%',
        rawValue: 76.4,
        changePct: -12.8,
        positive: false,
        hint: 'Target ≥ 90%',
        samples: [95, 94, 93, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82.5, 82, 81, 80.5, 80, 79.5, 79, 78.5, 78, 77.5, 77.2, 77, 76.8, 76.6, 76.5, 76.4, 76.4, 76.4],
      },
      {
        id: 'deploymentFrequency',
        label: 'Deploys per week',
        value: '38',
        rawValue: 38,
        changePct: 6.1,
        positive: true,
        hint: 'vs. previous 30 days',
        samples: [22, 24, 23, 28, 27, 30, 31, 29, 33, 32, 36, 34, 37, 35, 39, 38, 40, 37, 39, 38, 41, 38, 39, 37, 40, 39, 38, 42, 39, 38],
      },
    ],
  },
  web: {
    updatedAt: Date.now() / 1000,
    cards: [
      {
        id: 'successRate',
        label: 'Deploy success rate',
        value: '97.1%',
        rawValue: 97.1,
        changePct: 0.8,
        positive: true,
        hint: '30-day rolling window',
        samples: [94, 95, 95, 96, 96, 95, 97, 97, 96, 98, 97, 98, 97, 96, 98, 99, 97, 98, 98, 97, 98, 99, 98, 98, 97, 99, 98, 98, 97, 97],
      },
      {
        id: 'activeServices',
        label: 'Active services',
        value: '8',
        rawValue: 8,
        changePct: 0,
        positive: false,
        hint: 'No change this month',
        samples: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
      },
      {
        id: 'errorBudget',
        label: 'Error budget left',
        value: '64.2%',
        rawValue: 64.2,
        changePct: -21.5,
        positive: false,
        hint: 'Below ≥ 90% target',
        samples: [82, 81, 80, 79, 78.5, 78, 77, 76, 75.5, 75, 74, 73.5, 73, 72.5, 72, 71.5, 71, 70.5, 70, 69.5, 69, 68, 67, 66.5, 66, 65.5, 65.2, 65, 64.5, 64.2],
      },
      {
        id: 'deploymentFrequency',
        label: 'Deploys per week',
        value: '27',
        rawValue: 27,
        changePct: 3.8,
        positive: true,
        hint: 'vs. previous 30 days',
        samples: [18, 19, 20, 21, 22, 21, 23, 24, 23, 25, 24, 26, 25, 27, 26, 28, 27, 26, 28, 27, 29, 28, 27, 28, 27, 29, 28, 27, 28, 27],
      },
    ],
  },
  data: {
    updatedAt: Date.now() / 1000,
    cards: [
      {
        id: 'successRate',
        label: 'Deploy success rate',
        value: '99.9%',
        rawValue: 99.9,
        changePct: 0.1,
        positive: true,
        hint: '30-day rolling window',
        samples: [99, 100, 99, 100, 100, 99, 100, 100, 99, 100, 100, 99, 100, 99, 100, 100, 99, 100, 100, 99, 100, 99, 100, 99, 100, 99, 100, 100, 99, 99],
      },
      {
        id: 'activeServices',
        label: 'Active services',
        value: '5',
        rawValue: 5,
        changePct: -16.7,
        positive: false,
        hint: '−1 decommissioned',
        samples: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      },
      {
        id: 'errorBudget',
        label: 'Error budget left',
        value: '91.3%',
        rawValue: 91.3,
        changePct: 4.2,
        positive: true,
        hint: 'Target ≥ 90%',
        samples: [86, 87, 87.5, 88, 88.5, 89, 89.2, 89.5, 90, 90, 90.2, 90.5, 90.5, 90.8, 91, 91, 91.1, 91.1, 91.2, 91.2, 91.2, 91.2, 91.3, 91.3, 91.3, 91.3, 91.3, 91.3, 91.3, 91.3],
      },
      {
        id: 'deploymentFrequency',
        label: 'Deploys per week',
        value: '12',
        rawValue: 12,
        changePct: -14.3,
        positive: false,
        hint: 'vs. previous 30 days',
        samples: [14, 14, 13, 13, 13, 12, 12, 12, 11, 12, 12, 11, 12, 12, 11, 12, 12, 11, 12, 12, 12, 11, 12, 12, 12, 11, 12, 12, 12, 12],
      },
    ],
  },
}